# This is a basic workflow to help you get started with Actions

name: Python

on:
  push: # supposed to be comment for master merge only
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  build:
    runs-on: ubuntu-latest
#     if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
      - name: Install PyGithub & Execute py script
        id: demoId
        uses:  ./.github/actions/pyGithubSetup
        with:
          REPO_NAME: ${{ github.event.repository.name }}  
          ACCESS_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
          USER_NAME: ${{ github.actor }}
