# This is a basic workflow to help you get started with Actions

name: Python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install PyGithub & Execute py script
        id: demoId
        uses:  ./.github/actions/pyGithubSetup
        with:
          REPO_NAME: ${{ github.event.repository.name }}  
          ACCESS_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
          USER_NAME: ${{ github.actor }}
